### ISSUE TITLE
pytorch version missing

### ISSUE THREAD

**Issue by whonor** [Veason-silverbullet/UniTRec#2]
Hi there, which pytorch version is available ?
Thanks.

**Comment by Veason-silverbullet** [comment]
If the code has any bug, I must fix it. However, some basic questions like the torch version here should be addressed by yourself. I am out of university now and I don't have a machine to download&run&check the torch version. Please try the torch version by yourself.

As I remember, I answered your issues in another repo two years ago. It took me some time and effort, and I got nothing.
